<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<title><?=$this->pageTitle ?></title>

<script type="text/javascript" src="http://minify.enorange.cn/?b=resource/ext&f=jub.js,jquery.ndd.js"></script>
<script type="text/javascript" src="http://minify.enorange.cn/?b=resource/form/script&f=admin.js,main.js,admin-back.js,admin-drag.js"></script>
<script type="text/javascript" src="http://minify.enorange.cn/?b=resource/form/v1/script&f=attributeset.js,ajax-select-grid.js"></script>

<link rel="stylesheet" href="<?=Class_Server::getExtUrl()?>/reset.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::getExtUrl()?>/admin/toolbar.css" type="text/css" media="screen, projection">

<link type="text/css" rel="stylesheet" href="http://minify.enorange.cn/?b=resource/ext/admin&f=links.css,head-desc.css,footer.css&debug=1" />
<link type="text/css" rel="stylesheet" href="http://minify.enorange.cn/?b=resource/form/v1/style&f=admin-structure.css,form-editor.css" />

<script>
window.ORG_CODE = "<?php echo Class_Server::getOrgCode()?>";
</script>