<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<title><?=$this->pageTitle ?></title>

<link rel="stylesheet" href="http://library.enorange.com/ext/reset.css" type="text/css" media="screen, projection">
<script type="text/javascript" src="<?=Class_Server::getExtUrl()?>/jub.js"></script>
<script type="text/javascript" src="http://lib.eo.test/v1/script/admin.js"></script>
<script type="text/javascript" src="http://library.enorange.com/v1/script/ajax-select-grid.js"></script>

<script type="text/javascript" src="http://lib.eo.test/form/script/main.js"></script>
<script type="text/javascript" src="http://lib.eo.test/ext/jquery.ndd.js"></script>
<script type="text/javascript" src="http://lib.eo.test/v1/script/admin-drag.js"></script>

<link rel="stylesheet" href="<?=Class_Server::getExtUrl()?>/admin/toolbar.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::getExtUrl()?>/admin/links.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="http://library.enorange.com/v1/style/template.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="http://library.enorange.com/v1/style/admin-structure.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="http://library.enorange.com/v1/style/admin-backend.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?php echo Class_Server::getLibUrl()?>/style/form-editor.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?php echo Class_Server::getLibUrl()?>/style/admin.css" type="text/css" media="screen" rel="stylesheet">

<?=$this->headScript() ?>