<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >
<title><?=$this->pageTitle ?></title>

<link rel="stylesheet" href="http://lib.eo.test/ext/reset.css" type="text/css" media="screen, projection">
<script type="text/javascript" src="<?=Class_Server::getExtUrl()?>/jub.js"></script>
<script type="text/javascript" src="<?=Class_Server::getExtUrl()?>/jquery.ndd.js"></script>
<script type="text/javascript" src="<?php echo Class_Server::getLibUrl()?>/v1/script/attributeset.js"></script>

<script type="text/javascript" src="<?php echo Class_Server::getLibUrl()?>/script/admin.js"></script>
<script type="text/javascript" src="<?php echo Class_Server::getLibUrl()?>/script/ajax-select-grid.js"></script>

<script type="text/javascript" src="<?php echo Class_Server::getLibUrl()?>/script/main.js"></script>
<!-- script type="text/javascript" src="http://lib.eo.test/ext/jquery.ndd.js"></script -->
<script type="text/javascript" src="<?php echo Class_Server::getLibUrl()?>/script/admin-drag.js"></script>

<link rel="stylesheet" href="<?=Class_Server::getExtUrl()?>/admin/toolbar.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::getExtUrl()?>/admin/links.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::getExtUrl()?>/admin/head-desc.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="<?=Class_Server::getExtUrl()?>/admin/footer.css" type="text/css" media="screen, projection">



<link rel="stylesheet" href="<?php echo Class_Server::getLibUrl()?>/v1/style/admin-structure.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?php echo Class_Server::getLibUrl()?>/v1/style/form-editor.css" type="text/css" media="screen" rel="stylesheet">
<!-- <link rel="stylesheet" href="http://library.enorange.com/v1/style/template.css" type="text/css" media="screen, projection">
<link rel="stylesheet" href="http://library.enorange.com/v1/style/admin-backend.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?php echo Class_Server::getLibUrl()?>/style/form-editor.css" type="text/css" media="screen" rel="stylesheet">
<link rel="stylesheet" href="<?php echo Class_Server::getLibUrl()?>/style/admin.css" type="text/css" media="screen" rel="stylesheet"> -->

<?//=$this->headScript() ?>