<?php
$naviArr = array(
	array(
		'title' => '表单管理'
	)
);

$request = Zend_Controller_Front::getInstance()->getRequest();
?>

<?=$this->doctype() ?>
<html>
<head>
<?=$this->partial('head.phtml', $this) ?>
</head>

<body>
	<?php echo $this->extension('Navi', $naviArr) ?>

	<div id='admin_main_frame'>
		<div class='desc'>
			<div class='head'>
				<?php echo $this->head?>
			</div>
		</div>
		
		<?php echo $this->extension('ActionMenu', $this->actionMenu) ?>
		
		<div class='flash-message'>
		<?php 
			$messenger = new Zend_Controller_Action_Helper_FlashMessenger();
			$messages = $messenger->getMessages();
			if(count($messages) > 0) {
		?>
			<div class='brick-admin-flash-message'>
		<?php	
				foreach($messages as $m) {
					echo "<div>".$m."</div>";
				}
		?>
			</div>
		<?php
			}
		?>
		</div>
		
		<div class='under-desc'>
			<?=$this->layout()->content ?>
		</div>
	</div>
	<div class='footer'>
		<hr />
		<div class='power'>
			powered by <a href='http://www.enorange.com'>Enorange Ltd</a>
		</div>
	</div>
</body>
</html>