<li class='drag-dropable'></li>
<li draggable="true" class="solid drag-handle">
	<div class="element-label">
		<a href="/<?php echo Class_Server::getOrgCode();?>/admin/element/edit/id/<?php echo $this->testid;?>" class="lightbox-trigger">标题</a>
	</div>
	<div class="element">
		<input type="checkbox" value="" name="" disabled="disabled">
		<label>第一选项</label>
		<input type="checkbox" value="" name="" disabled="disabled">
		<label>第二选项</label>
		<input type="checkbox" value="" name="" disabled="disabled">
		<label>第三选项</label>
	</div>
	<div class="element-desc">标题描述</div><div class="element-controller"></div>
</li>