
<li draggable="true" class="solid drag-handle" id="form_element" org-id="<?php echo $this->testid;?>">
	<div class="element-label">
		<a href="/<?php echo Class_Server::getOrgCode();?>/admin/element/edit/id/<?php echo $this->testid;?>" class="lightbox-trigger" draggable="false">标题</a>
	</div>
	<div class="element"><input type="" disabled="disabled"></div>
	<div class="element-desc">标题描述</div><div class="element-controller"></div>
</li>	