<style>
.attribute-library {
	width: 350px;
	border-radius: 4px;
	background: #eee;
	padding: 25px;
	margin: 15px;
	position: fixed; 
}
.attribute-library .attribute-library-item {
	background: #bbb;
	cursor:pointer;
	height:32px;
	line-height:32px;
	border-radius: 4px 4px 4px 4px;
	margin-top:5px;
	box-shadow: 1px 1px 1px #777777;
}
.attribute-library-item span{
	height:32px;
	width:32px;
	display:block;
}
.attribute-library-itemfrom{
	background: #EEEEEE;
	height:32px;
	line-height:32px;
}
.attribute-library-itemfrom span{
	height:32px;
	width:32px;
	display:block;
}
.attribute-library-item:hover{
	box-shadow: -1px -1px 1px #777777;
}
</style>
	<div class="attribute-library">
		<div class="attribute-library-itemfrom" label="表单">
			<span style="float:left;background:url('/images/form-element.png') no-repeat scroll 0px 0px transparent;"></span>
			<div style="float:left;font-weight:bold;">from表单元素</div>
		</div>
		<div class="attribute-library-item" attribute-type="text" label="输入框" >
			<span style="float:left;margin-left:5px;background:url('/images/form-element.png') no-repeat scroll -32px 0px transparent;"></span>
			<div style="float:left;margin-left:10px;">输入框</div>

		</div>
		<div class="attribute-library-item" attribute-type="select" label="单选按钮">
			<span style="float:left;margin-left:5px;background:url(/images/form-element.png) no-repeat scroll -65px 0px transparent;"></span>
			<div style="float:left;margin-left:10px;">单选框</div>
		</div>
		<div class="attribute-library-item" attribute-type="multi-checkbox" label="多选框">
			<span style="float:left;margin-left:5px;background:url(/images/form-element.png) no-repeat scroll -128px 0px transparent;"></span>
			<div style="float:left;margin-left:10px;">多选框</div>
		</div>
		<div class="attribute-library-item" attribute-type="menu" label="单选下拉框">
			<span style="float:left;margin-left:5px;background:url(/images/form-element.png) no-repeat scroll -160px 0px transparent;"></span>
			<div style="float:left;margin-left:10px;">下拉菜单框</div>
		</div>
		<div class="attribute-library-item" attribute-type="textarea" label="文本域">
			<span style="float:left;margin-left:5px;background:url('/images/form-element.png') no-repeat scroll -96px 0px transparent;"></span>
			<div style="float:left;margin-left:10px;">文本域</div>

		</div>
		<div class="attribute-library-item" attribute-type="button" label="提交按钮">
			<span style="float:left;margin-left:5px;background:url('/images/form-element.png') no-repeat scroll 0px -34px transparent;"></span>
			<div style="float:left;margin-left:10px;">提交按钮</div>
		</div>
	</div>
  <input type="hidden" id="formname" name="formname" value="<?php echo $this->formid;?>"/>
  <input type="hidden" id="orgcode" name="orgcode" value="<?php echo Class_Server::getOrgCode()?>"/>
<div class='element-current' style='min-height: 350px;'>
	<ul class='form-editor'>
		<li class='element-dropable'></li>
	<?php
	foreach($this->formElementList as $row) {
		$html = "<li id='form_element' org-id='".$row['_id']."' class='solid drag-handle' draggable='true'><div class='element-label'>";
		if($row['elementType'] != 'button'){
			$html.= "<a draggable='false' class='lightbox-trigger' href='/".Class_Server::getOrgCode()."/admin/element/edit/id/".$row['_id']."'>".$row['label']."</a></div><div class='element'>";
			switch($row['elementType']) {
				case 'text':
					$html.= "<input type='text' disabled='disabled'>";
					break;
				case 'textarea':
					$html.= "<textarea disabled='disabled'></textarea>";
					break;
				case 'select':
					foreach($row['option'] as $arrone){
						$html.= "<input type='radio' disabled='disabled' name='' value=''><label>".$arrone."</label>";
					}
					break;
				case 'multi-checkbox':
					foreach($row['option'] as $arrone){
						$html.= "<input type='checkbox' disabled='disabled' name='' value=''><label>".$arrone."</label>";
					}
					break;
				case 'menu':
					$html.= "<select disabled='disabled' style='width:100px'><option></option></select><br />";
					foreach($row['option'] as $arrone){
						$html.= $arrone."&nbsp;&nbsp;&nbsp;&nbsp;";
					}
					break;
			}
			$html.= "</div><div class='element-desc'>".$row['desc']."</div><div class='element-controller'></div>";
		} else {
			$html.= "<a draggable='false' class='lightbox-trigger' href='/".Class_Server::getOrgCode()."/admin/element/editbutton/id/".$row['_id']."'>";
			$html.="<input type='submit' name='button' id='button' value='".$row['label']."' /></a></div><div class='element'>";
		}
		echo $html;
		echo "</li><li class='drag-dropable'></li><li class='element-dropable'></li>";
	}
	?>
	</ul>
</div>

<script type='text/javascript'>
$('.action-menu').click(function(){
	var elementid = '';
	$("li[id='form_element']").each(function(){
		elementid+= $(this).attr("org-id")+':';
	});
	$.ajax({
		type: "POST",
		url: '/<?php echo Class_Server::getOrgCode();?>/admin/form/sort/',
		data: "val="+elementid,
		success: function(obj) {
			location.href = "/<?php echo Class_Server::getOrgCode();?>/admin";
		}
	});
	return false;
});
$('.attribute-library .attribute-library-item').click(function(){
	var formid = $('#formname').val();
	var type = $(this).attr('attribute-type');
	var resp = $.ajax({
		type: "POST",
		url: '/'+<?php echo Class_Server::getOrgCode()?>+'/admin/form/get-element-template/type/' + type + '/id/' + formid + '/format/html',
		success: function(html) {
			if(resp.getResponseHeader('result') == 'success') {
				//$('#add-element').html(html);
				$(".element-dropable").eq(0).after(html);
			} else {
				alert('error');
			}
		}
	});
	//alert($(this).attr('attribute-type'));
});
</script>